config/routes.rb
Biblio::Application.routes.draw do

  resources :parser, :only => [:index, :create]
  
  resources :api, :only => :index
  
  resources :train, :only => [:create, :destroy]

  resources :plugins, :only => [:index]
  
  namespace :plugins do
    resources :refparser, :only => [:index]
    resources :grabtag, :only => [:index]
  end

  root :to => 'home#index'

end

app/controllers/plugins/grabtag_controller.rb
class Plugins::GrabtagController < ApplicationController
  caches_page :index

  def index
    @references = [
      "<strong>Buddle</strong>, C.M. and D.P. Shorthouse. (2008). Effects of experimental harvesting on spider (Araneae) assemblages in boreal deciduous forests. <em>The Canadian Entomologist</em> <span data-grabtag='volume'>140(4)</span>: 437-452, 10.4039/n07-LS01"
    ]
  end
end

app/controllers/plugins/refparser_controller.rb
class Plugins::RefparserController < ApplicationController
  caches_page :index

  def index
    @references = [
      "DeMaster, D., I. Stirling. 1981. *Ursus maritimus*. Mammalian Species, 145: 1-7.",
      "Epling, C., Lewis H., & Ball F. M. (1960). The Breeding Group and Seed Storage: A Study in Population Dynamics. Evolution. 14, 238-255.",
      "MACDONALD, S., & FENNIAK T. (2007). Understory plant communities of boreal mixedwood forests in western Canada: Natural patterns and response to variable-retention harvesting. Forest Ecology and Management. 242(1): 34-48.",
      "Williston, Samuel W. (1908). Manual of North American Diptera. New Haven: J.T. Hathaway."
    ]
  end
end

app/controllers/plugins_controller.rb
class PluginsController < ApplicationController
  caches_page :index
  
  def index
  end
end

app/helpers/plugins_helper.rb
module PluginsHelper
end

app/views/plugins/index.html.erb
<% title "jQuery Plugins" %>

<%- content_for :content_splash do -%>
<%= content_tag :h2, "jQuery Plugins" %>
<%- end -%>

<div id="panel-wrapper" class="clear">

<div class="panel">
<h3><%= link_to "RefParser", plugins_refparser_index_path %></h3>
<p>Seamlessly embed parsing and discovery in your online bibliographic citations and use the callback functions to crowd-source DOI capture.</p>
</div>

<div class="panel">
<h3><%= link_to "GrabTag", plugins_grabtag_index_path %></h3>
<p>Empower users to mark-up your content and provide semantic meaning to words, phrases, or more.</p>
</div>

</div>