config/routes.rb
Biblio::Application.routes.draw do

  resources :parser, :only => [:index, :create]
  
  resources :api, :only => :index
  
  resources :train, :only => [:create, :destroy]

  resources :plugins, :only => [:index]
  
  namespace :plugins do
    resources :refparser, :only => [:index]
    resources :grabtag, :only => [:index]
  end

  root :to => 'home#index'

end

app/views/layouts/_footer.html.erb
<div id="Footer" class="structural fixedWidth">
  <div class="inner">
      <span><%= link_to 'Global Names Architecture', 'http://www.globalnames.org' %></span>|
      <span><%= link_to 'Global Names Index', 'http://gni.globalnames.org' %></span>|
      <span><%= link_to 'Global Names Classification and List Repository', 'http://gnaclr.globalnames.org' %></span>|
      <span><%= link_to 'Global Names Integrated Taxonomic Editor', 'http://gnite.org' %></span>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="Header" class="structural fixedWidth">
  <div class="inner">
    <div id="Logo">
      <a href="/">
        <h1>Global Names Biblio Tools</h1>
      </a>
    </div>
    <ul id="SiteNavigation">
      <%- if controller_name == "home" -%>
        <li class="active"><%= link_to "Home", root_path %></li>
      <%- else -%>
        <li><%= link_to "Home", root_path %></li>
      <%- end -%>
      <%- if controller_name == "parser" -%>
        <li class="active"><%= link_to "Parser", parser_index_path %></li>
      <%- else -%>
        <li><%= link_to "Parser", parser_index_path %></li>
      <%- end -%>
      <%- if controller_name == "api" -%>
        <li class="active"><%= link_to "API", api_index_path %></li>
      <%- else -%>
        <li><%= link_to "API", api_index_path %></li>
      <%- end -%>
      <%- if controller_path.include? "plugins" -%>
        <li class="active"><%= link_to "jQuery Plugins", plugins_path %></li>
      <%- else -%>
        <li><%= link_to "jQuery Plugins", plugins_path %></li>
      <%- end -%>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? "Global Names Biblio Tools :: " << content_for(:title) : "Global Names Biblio Tools" %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="SiteContainer" class="structural">

    <div class="background"></div>

    <%= render :partial => 'layouts/header' %>

   <div id="BodyContent" class="structural fixedWidth clear">
     <div class="inner">
       <div id="content-wrapper">
         <%- flash.each do |name, msg| -%>
           <%= content_tag :div, msg, :id => "flash_#{name}" %>
         <%- end -%>
         <%- if content_for?(:content_splash) -%>
           <div id="content-splash">
             <%=  content_for(:content_splash) %>
           </div>
         <%- end -%>
         <div id="content-body">
           <%= yield %>
         </div>
         <%- if content_for?(:content_features) -%>
           <div id="content-features" class="clear">
             <%= content_for(:content_features) %>
           </div>
         <%- end -%>
       </div>
     </div>
   </div>

   <%= render :partial => 'layouts/footer' %>

  </div>
</body>
</html>